float64[7] q                # subsystem_buffer{type: port}
float64[7] dq               # subsystem_buffer{type: port}
float64[7] t                # subsystem_buffer{type: port}
float64[7] gt               # subsystem_buffer{type: port}
geometry_msgs/Wrench w      # subsystem_buffer{type: port}
float64[28] mmx             # subsystem_buffer{type: port}
FriIntfState iState         # subsystem_buffer{type: port}
FriRobotState rState        # subsystem_buffer{type: port}

